using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

namespace FeniStudio {
    public class CodeProject {
        public string[] Code=new string[15];
        public int[] Duration=new[]{1800,4200,0,1400,0,0,0,0,0,0,0,0,0,0,0};
        public static string ProjectPath {get{return Path.Combine(StudioConfig.DirectoryPath,"animations-code.json");}}
        public static CodeProject Load(){var p=File.Exists(ProjectPath)?new JavaScriptSerializer().Deserialize<CodeProject>(File.ReadAllText(ProjectPath)):new CodeProject();p.Validate();if(String.IsNullOrWhiteSpace(p.Code[1])&&p.Duration[1]==2400)p.Duration[1]=4200;return p;}
        public void Validate(){if(Code==null||Code.Length!=15||Duration==null||Duration.Length!=15)throw new InvalidDataException("Invalid animation code project; the original file was preserved.");for(int i=0;i<15;i++){Code[i]=Code[i]??"";if(Code[i].Length>100000)throw new InvalidDataException("Keep each animation under 100,000 characters.");if(Slots.Event(i)&&(Duration[i]<100||Duration[i]>10000))throw new InvalidDataException("Event duration must be 100–10000 ms.");}}
        public void Save(){Validate();Directory.CreateDirectory(StudioConfig.DirectoryPath);string temp=ProjectPath+".new";File.WriteAllText(temp,new JavaScriptSerializer().Serialize(this));if(File.Exists(ProjectPath))File.Replace(temp,ProjectPath,ProjectPath+".bak");else File.Move(temp,ProjectPath);}
        [ScriptIgnore]
        public string Revision {get{using(var sha=SHA256.Create()){return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(this)))).Replace("-","").Substring(0,12).ToLowerInvariant();}}}
        public string Header(){
            Validate();var b=new StringBuilder("#pragma once\n// Generated by Feni Studio. Edit behaviour code in the app.\n");
            b.Append("const char *codeRevision=\"").Append(Revision).Append("\";\n");
            b.Append("bool hasUserAnimation(uint8_t slot) { switch(slot) {\n");
            for(int i=0;i<15;i++)if(!String.IsNullOrWhiteSpace(Code[i]))b.Append("case ").Append(i).Append(":return true;\n");
            b.Append("default:return false;}}\nuint32_t userAnimationDuration(uint8_t slot) {switch(slot) {\n");
            for(int i=0;i<15;i++)if(Slots.Event(i))b.Append("case ").Append(i).Append(":return ").Append(Duration[i]).Append(";\n");
            b.Append("default:return 0;}}\n");
            for(int i=0;i<15;i++)if(!String.IsNullOrWhiteSpace(Code[i])){b.Append("bool codeSlot").Append(i).Append("(BuddyCanvas &canvas,uint32_t elapsed,uint32_t now) {\n#line 1 \"behaviour-").Append(i).Append(".cpp\"\n").Append(Code[i]).Append("\nreturn true;\n}\n");}
            b.Append("bool drawUserAnimation(BuddyCanvas &canvas,uint8_t slot,uint32_t elapsed,uint32_t now) {switch(slot){\n");
            for(int i=0;i<15;i++)if(!String.IsNullOrWhiteSpace(Code[i]))b.Append("case ").Append(i).Append(":return codeSlot").Append(i).Append("(canvas,elapsed,now);\n");
            return b.Append("default:return false;}}\n").ToString();
        }
        public const string Example="// Draw one animation update. elapsed/now are milliseconds.\r\n// 0 = black, 1 = eye/theme colour, 2 = accent, 3 = dim accent.\r\nint height = ((elapsed % 4000) < 150) ? 4 : 38;\r\ncanvas.fillRoundRect(36, 64-height/2, 34, height, 6, 1);\r\ncanvas.fillRoundRect(90, 64-height/2, 34, height, 6, 1);\r\n";
    }
    public static class FirmwareBuilder {
        public const string Board="esp8266:esp8266:nodemcuv2:mmu=4816H,eesz=4M1M";
        public static string DefaultCli {get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs","arduino-ide","resources","app","lib","backend","resources","arduino-cli.exe");}}
        public static string Quote(string value){if(value.IndexOfAny(new[]{'\"','\r','\n'})>=0)throw new ArgumentException("Invalid command argument");return "\""+value.TrimEnd('\\')+"\"";}
        public static string Prepare(string source,CodeProject project,string root){
            if(!File.Exists(Path.Combine(source,"FeniBuddy.ino")))throw new IOException("Choose the FeniBuddy firmware folder.");
            if(!File.Exists(Path.Combine(source,"CodeAnimations.h")))throw new IOException("Use firmware 3.5.0 or later for animation code.");
            string sketch=Path.Combine(root,"FeniBuddy");Copy(source,sketch);File.WriteAllText(Path.Combine(sketch,"CustomAnimations.h"),project.Header(),new UTF8Encoding(false));return sketch;
        }
        static void Copy(string source,string destination){Directory.CreateDirectory(destination);foreach(string file in Directory.GetFiles(source)){string ext=Path.GetExtension(file).ToLowerInvariant();if(new[]{".ino",".h",".hpp",".c",".cpp",".s",".a"}.Contains(ext))File.Copy(file,Path.Combine(destination,Path.GetFileName(file)),true);}string src=Path.Combine(source,"src");if(Directory.Exists(src))CopyTree(src,Path.Combine(destination,"src"));}
        static void CopyTree(string source,string destination){Directory.CreateDirectory(destination);foreach(string file in Directory.GetFiles(source))File.Copy(file,Path.Combine(destination,Path.GetFileName(file)),true);foreach(string dir in Directory.GetDirectories(source))CopyTree(dir,Path.Combine(destination,Path.GetFileName(dir)));}
        public static async Task<string> Build(StudioConfig config,CodeProject project,bool flash,Action<string> log){
            if(!File.Exists(config.ArduinoCli))throw new IOException("Choose arduino-cli.exe in Build & flash.");
            if(flash && !System.Text.RegularExpressions.Regex.IsMatch(config.Port??"","^COM[0-9]+$",System.Text.RegularExpressions.RegexOptions.IgnoreCase))throw new IOException("Choose Feni's USB COM port.");
            string root=Path.Combine(StudioConfig.DirectoryPath,"builds",DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6));
            string sketch=Prepare(config.FirmwareFolder,project,root),output=Path.Combine(root,"output");
            log("Building saved animation code " + project.Revision + "...\r\n");
            int result=await Run(config.ArduinoCli,"compile --fqbn "+Board+" --build-path "+Quote(output)+" "+Quote(sketch),root,log);
            if(result!=0)throw new IOException("Build failed. Feni was not flashed. See the compiler log.");
            if(flash){log("\r\nFlashing "+config.Port+"...\r\n");result=await Run(config.ArduinoCli,"upload --fqbn "+Board+" --port "+config.Port+" --input-dir "+Quote(output)+" "+Quote(sketch),root,log);if(result!=0)throw new IOException("USB upload failed. Check the cable and COM port, then retry.");}
            log("\r\n"+(flash?"Flashed successfully. Feni is restarting.":"Build passed. Feni was not changed.")+"\r\nBuild files: "+root+"\r\n");return root;
        }
        static Task<int> Run(string exe,string args,string root,Action<string> log){return Task.Run(()=>{using(var p=new Process()){p.StartInfo=new ProcessStartInfo(exe,args){WorkingDirectory=root,UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};p.OutputDataReceived+=(s,e)=>{if(e.Data!=null)log(e.Data+"\r\n");};p.ErrorDataReceived+=(s,e)=>{if(e.Data!=null)log(e.Data+"\r\n");};p.Start();p.BeginOutputReadLine();p.BeginErrorReadLine();p.WaitForExit();return p.ExitCode;}});}
    }
}
