using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.IO.Ports;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
namespace FeniStudio {
    class StudioForm : Form {
        static readonly Color Bg=Color.FromArgb(12,17,24),Card=Color.FromArgb(22,30,41),Ink=Color.FromArgb(231,237,244),Muted=Color.FromArgb(152,166,184),Accent=Color.FromArgb(70,214,224);
        StudioConfig config;CodeProject project;DeviceClient device;string installedRevision="";bool busy=false,quitting=false;int aiOverride=-1;
        Label status,deviceInfo,ruleState,codeHint;TextBox url,cliPath,firmwarePath;RichTextBox editor,buildLog;
        ListBox behaviours;NumericUpDown duration;int editingSlot=-1;ComboBox ports;
        DataGridView rules;BindingList<AppRule> ruleList;CheckBox enabled;TabControl tabs;NotifyIcon tray;
        readonly System.Windows.Forms.Timer heartbeat=new System.Windows.Forms.Timer();
        public StudioForm(StudioConfig c,bool hidden){
            config=c;project=CodeProject.Load();Text="Feni Studio";BackColor=Bg;ForeColor=Ink;Font=new Font("Segoe UI",10);ClientSize=new Size(1180,730);MinimumSize=new Size(980,650);StartPosition=FormStartPosition.CenterScreen;AutoScaleMode=AutoScaleMode.Dpi;
            var header=new Panel {Dock=DockStyle.Top,Height=90};header.Controls.Add(new Label {Text="FENI STUDIO",Font=new Font("Segoe UI",23,FontStyle.Bold),AutoSize=true,Location=new Point(23,9),ForeColor=Accent});header.Controls.Add(new Label {Text="Animation code and application reactions",AutoSize=true,Location=new Point(26,53),ForeColor=Muted});Controls.Add(header);
            var footer=new Panel {Dock=DockStyle.Bottom,Height=45,Padding=new Padding(24,10,20,8)};status=new Label {Dock=DockStyle.Fill,Text="Choose a behaviour to edit its animation code.",ForeColor=Muted,AutoEllipsis=true};footer.Controls.Add(status);Controls.Add(footer);
            tabs=new TabControl {Dock=DockStyle.Fill,Padding=new Point(16,10)};Controls.Add(tabs);tabs.BringToFront();BuildCode();BuildRules();BuildFirmware();BuildDevice();
            heartbeat.Interval=2000;heartbeat.Tick+=async delegate {await SendActivity();};heartbeat.Start();
            tray=new NotifyIcon {Icon=SystemIcons.Application,Text="Feni Studio",Visible=true};var menu=new ContextMenuStrip();menu.Items.Add("Open Feni Studio",null,delegate {ShowApp();});var aiMenu=new ToolStripMenuItem("AI state");foreach(int value in new[]{-1,0,1,2}){int chosen=value;var item=new ToolStripMenuItem(value<0?"Automatic":AiStatus.Name(value)){Checked=value<0};item.Click+=delegate {aiOverride=chosen;foreach(ToolStripMenuItem choice in aiMenu.DropDownItems)choice.Checked=choice==item;};aiMenu.DropDownItems.Add(item);}menu.Items.Add(aiMenu);menu.Items.Add("Quit",null,delegate {quitting=true;Close();});tray.ContextMenuStrip=menu;tray.DoubleClick+=delegate {ShowApp();};
            FormClosing+=delegate(object sender,FormClosingEventArgs e){if(busy){e.Cancel=true;status.Text="Wait for the current operation to finish before closing.";return;}try{SaveCode();}catch(Exception ex){e.Cancel=true;Error(ex);return;}if(!quitting&&e.CloseReason==CloseReason.UserClosing){e.Cancel=true;Hide();}};
            FormClosed+=delegate {tray.Dispose();heartbeat.Dispose();if(device!=null)device.Dispose();};
            Shown+=async delegate {if(hidden)Hide();busy=true;try{await Connect();}catch(Exception ex){status.Text="Offline: "+ex.Message;}finally{busy=false;}};
        }
        protected override void WndProc(ref Message m){if(m.Msg==Program.ShowMessage)ShowApp();base.WndProc(ref m);}
        void ShowApp(){Show();WindowState=FormWindowState.Normal;Activate();}
        TabPage Tab(string title){var p=new TabPage(title){BackColor=Card,ForeColor=Ink,Padding=new Padding(14)};tabs.TabPages.Add(p);return p;}
        Button Button(string text,Action action,int width=145){var b=new Button {Text=text,Width=width,Height=36,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(34,48,62),ForeColor=Ink,Margin=new Padding(0,0,8,8)};b.FlatAppearance.BorderColor=Color.FromArgb(61,79,94);b.Click+=delegate {try{action();}catch(Exception ex){Error(ex);}};return b;}
        Button AsyncButton(string text,Func<Task> action,int width=145){return Button(text,async delegate {await Work(action);},width);}
        FlowLayoutPanel Actions(){return new FlowLayoutPanel {Dock=DockStyle.Bottom,AutoSize=true,MinimumSize=new Size(0,45),WrapContents=true};}
        DataGridView Grid(){var g=new DataGridView {Dock=DockStyle.Fill,BackgroundColor=Card,BorderStyle=BorderStyle.None,AllowUserToAddRows=false,AllowUserToDeleteRows=false,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoGenerateColumns=false,EnableHeadersVisualStyles=false,AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.None};g.RowTemplate.Height=33;g.DefaultCellStyle.BackColor=Card;g.DefaultCellStyle.ForeColor=Ink;g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(40,77,91);g.DefaultCellStyle.SelectionForeColor=Ink;g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(32,44,57);g.ColumnHeadersDefaultCellStyle.ForeColor=Ink;g.GridColor=Color.FromArgb(43,54,67);g.ColumnHeadersHeight=36;g.DataError+=delegate(object sender,DataGridViewDataErrorEventArgs e){e.ThrowException=false;status.Text="Choose a valid rule value.";};return g;}
        void Error(Exception e){status.Text=e.Message;MessageBox.Show(this,e.Message,"Feni Studio",MessageBoxButtons.OK,MessageBoxIcon.Information);}
        async Task Work(Func<Task> action){if(busy){status.Text="Wait for the current device operation to finish.";return;}busy=true;UseWaitCursor=true;try{await action();}catch(Exception ex){Error(ex);}finally{busy=false;UseWaitCursor=false;}}
        void Save(){rules.EndEdit();config.Rules=ruleList.ToList();config.RunRules=enabled.Checked;config.Url=url.Text.Trim();using(var test=new DeviceClient(config.Url)){}config.Save();status.Text="Configuration saved on this PC.";}
        void SaveCode(){if(editingSlot>=0){project.Code[editingSlot]=editor.Text;if(Slots.Event(editingSlot))project.Duration[editingSlot]=(int)duration.Value;}project.Save();RefreshRevisionInfo();}
        void SelectBehaviour(){SaveCode();editingSlot=behaviours.SelectedIndex;if(editingSlot<0)return;editor.Text=project.Code[editingSlot]??"";duration.Enabled=Slots.Event(editingSlot);duration.Value=Slots.Event(editingSlot)?project.Duration[editingSlot]:100;codeHint.Text=Slots.Names[editingSlot]+"  /  "+(Slots.Event(editingSlot)?"plays for the duration below":"runs while this behaviour is active")+"\nBlank code keeps the built-in animation. Save, then Build & flash to apply changes.";}
        void BuildCode(){
            var page=Tab("Animation code");var layout=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,185));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));page.Controls.Add(layout);
            behaviours=new ListBox {Dock=DockStyle.Fill,BackColor=Card,ForeColor=Ink,BorderStyle=BorderStyle.None,Font=new Font("Segoe UI",11),ItemHeight=29};behaviours.Items.AddRange(Slots.Names);layout.Controls.Add(behaviours,0,0);
            var body=new Panel {Dock=DockStyle.Fill,Padding=new Padding(14,0,0,0)};layout.Controls.Add(body,1,0);codeHint=new Label {Dock=DockStyle.Top,Height=62,ForeColor=Muted};body.Controls.Add(codeHint);
            editor=new RichTextBox {Dock=DockStyle.Fill,BackColor=Color.FromArgb(15,22,31),ForeColor=Ink,Font=new Font("Consolas",11),AcceptsTab=true,WordWrap=false,DetectUrls=false,BorderStyle=BorderStyle.FixedSingle};body.Controls.Add(editor);editor.BringToFront();editor.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.Control&&e.KeyCode==Keys.S){SaveCode();status.Text="Animation code saved locally.";e.SuppressKeyPress=true;}};
            var actions=Actions();actions.Controls.Add(Button("Save code",delegate {SaveCode();status.Text="Code saved. Build & flash applies it to Feni.";},115));actions.Controls.Add(Button("Import code",delegate {using(var d=new OpenFileDialog {Filter="C++ animation code|*.cpp;*.h;*.txt|All files|*.*"}){if(d.ShowDialog(this)==DialogResult.OK){var f=new FileInfo(d.FileName);if(f.Length>100000)throw new IOException("Code file is too large.");editor.Text=File.ReadAllText(d.FileName);status.Text="Imported into the editor. Save when ready.";}}},125));actions.Controls.Add(Button("Insert example",delegate {editor.SelectedText=CodeProject.Example;},140));actions.Controls.Add(Button("Use built-in",delegate {editor.Clear();SaveCode();status.Text="Built-in selected locally. Build & flash to apply.";},125));actions.Controls.Add(AsyncButton("Test installed code",async delegate {EnsureDevice();await device.Post("/code/test",Fields("slot",behaviours.SelectedIndex));status.Text="Testing the code currently flashed on Feni; local edits need Build & flash.";},180));
            duration=new NumericUpDown {Minimum=100,Maximum=10000,Increment=100,Width=95,Value=1800,Margin=new Padding(0,8,8,8)};var timing=new FlowLayoutPanel {Width=290,Height=44,Margin=new Padding(0),WrapContents=false};timing.Controls.Add(new Label {Text="Event duration (ms)",AutoSize=true,Margin=new Padding(0,10,8,0)});timing.Controls.Add(duration);actions.Controls.Add(timing);actions.Controls.Add(Button("Code guide",OpenGuide,110));body.Controls.Add(actions);behaviours.SelectedIndexChanged+=delegate {try{SelectBehaviour();}catch(Exception ex){Error(ex);}};behaviours.SelectedIndex=0;
        }
        TextBox PathRow(FlowLayoutPanel stack,string label,string value,bool folder){stack.Controls.Add(new Label {Text=label,AutoSize=true,ForeColor=Muted});var row=new FlowLayoutPanel {Width=1050,Height=45};var box=new TextBox {Text=value,Width=820,BackColor=Bg,ForeColor=Ink};row.Controls.Add(box);row.Controls.Add(Button("Browse",delegate {if(folder){using(var d=new FolderBrowserDialog()){d.Description="Choose the FeniBuddy firmware folder";if(d.ShowDialog(this)==DialogResult.OK)box.Text=d.SelectedPath;}}else{using(var d=new OpenFileDialog {Filter="Arduino CLI|arduino-cli.exe|Executable|*.exe"})if(d.ShowDialog(this)==DialogResult.OK)box.Text=d.FileName;}},100));stack.Controls.Add(row);return box;}
        void BuildFirmware(){
            var page=Tab("Build & flash");var top=new FlowLayoutPanel {Dock=DockStyle.Top,Height=245,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};page.Controls.Add(top);
            firmwarePath=PathRow(top,"Firmware source folder",config.FirmwareFolder,true);cliPath=PathRow(top,"Arduino CLI",config.ArduinoCli,false);
            var row=new FlowLayoutPanel {Width=1050,Height=50};row.Controls.Add(new Label {Text="USB port",AutoSize=true,Margin=new Padding(0,10,10,0)});ports=new ComboBox {Width=110,DropDownStyle=ComboBoxStyle.DropDown};ports.Items.AddRange(SerialPort.GetPortNames());ports.Text=config.Port;row.Controls.Add(ports);row.Controls.Add(Button("Refresh ports",delegate {string port=ports.Text;ports.Items.Clear();ports.Items.AddRange(SerialPort.GetPortNames());ports.Text=port;},130));row.Controls.Add(AsyncButton("Check / build",async delegate {await RunBuild(false);},135));row.Controls.Add(AsyncButton("Build & flash",async delegate {await RunBuild(true);},145));top.Controls.Add(row);top.Controls.Add(new Label {Text="Save your code, connect Feni by USB, then build. A failed build never flashes the device.\nWi-Fi settings and Calendar configuration are retained during an ordinary firmware upload.",AutoSize=true,ForeColor=Muted});
            buildLog=new RichTextBox {Dock=DockStyle.Fill,ReadOnly=true,BackColor=Bg,ForeColor=Ink,Font=new Font("Consolas",10),WordWrap=false,Text="Compiler output appears here. The first build can take several minutes.\n"};page.Controls.Add(buildLog);buildLog.BringToFront();
        }
        async Task RunBuild(bool flash){SaveCode();Save();config.ArduinoCli=cliPath.Text.Trim();config.FirmwareFolder=firmwarePath.Text.Trim();config.Port=ports.Text.Trim();config.Save();buildLog.Clear();var snapshot=new JavaScriptSerializer().Deserialize<CodeProject>(new JavaScriptSerializer().Serialize(project));status.Text=flash?"Building before USB flash...":"Checking animation code...";await FirmwareBuilder.Build(config,snapshot,flash,AppendLog);if(flash&&device!=null){device.Dispose();device=null;}status.Text=flash?"Flashed. Feni is restarting; Studio will reconnect.":"Build passed. Ready to flash.";}
        void AppendLog(string text){if(IsDisposed)return;if(InvokeRequired){BeginInvoke(new Action<string>(AppendLog),text);return;}buildLog.AppendText(text);buildLog.SelectionStart=buildLog.TextLength;buildLog.ScrollToCaret();}
        void BuildRules(){
            var page=Tab("App rules");page.Controls.Add(new Label {Dock=DockStyle.Top,Height=48,Text="First matching rule wins. Optional title matching is for foreground rules, e.g. YouTube in a browser.",ForeColor=Muted});
            rules=Grid();ruleList=new BindingList<AppRule>(config.Rules);rules.DataSource=ruleList;
            rules.Columns.Add(new DataGridViewCheckBoxColumn {HeaderText="On",DataPropertyName="Enabled",Width=40});rules.Columns.Add(new DataGridViewTextBoxColumn {HeaderText="Rule",DataPropertyName="Name",Width=110});rules.Columns.Add(new DataGridViewTextBoxColumn {HeaderText="Applications (.exe names, comma-separated)",DataPropertyName="Applications",AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill});
            rules.Columns.Add(new DataGridViewTextBoxColumn {HeaderText="Title contains (optional)",DataPropertyName="TitleContains",Width=190});
            var trigger=new DataGridViewComboBoxColumn {HeaderText="When",DataPropertyName="Trigger",Width=128,FlatStyle=FlatStyle.Flat};trigger.Items.AddRange("Foreground","Running");rules.Columns.Add(trigger);
            var choice=Enumerable.Range(4,11).Select(i=>new KeyValuePair<int,string>(i,Slots.Names[i])).ToList();rules.Columns.Add(new DataGridViewComboBoxColumn {HeaderText="Animation",DataPropertyName="Slot",DataSource=choice,ValueMember="Key",DisplayMember="Value",Width=150,FlatStyle=FlatStyle.Flat});page.Controls.Add(rules);rules.BringToFront();
            var actions=Actions();actions.Controls.Add(Button("Add rule",delegate {ruleList.Add(new AppRule());rules.CurrentCell=rules.Rows[rules.Rows.Count-1].Cells[1];},100));actions.Controls.Add(Button("Choose app .exe",ChooseExe,145));actions.Controls.Add(Button("Running apps",RunningApps,125));actions.Controls.Add(Button("Move up",delegate {MoveRule(-1);},90));actions.Controls.Add(Button("Move down",delegate {MoveRule(1);},100));actions.Controls.Add(Button("Remove rule",delegate {if(rules.CurrentRow!=null)ruleList.RemoveAt(rules.CurrentRow.Index);},115));actions.Controls.Add(Button("Save rules",Save,105));page.Controls.Add(actions);
        }
        void ChooseExe(){using(var d=new OpenFileDialog {Filter="Windows application|*.exe"}){if(d.ShowDialog(this)==DialogResult.OK)AddApp(Path.GetFileNameWithoutExtension(d.FileName));}}
        void AddApp(string name){if(rules.CurrentRow==null)ruleList.Add(new AppRule());int i=rules.CurrentRow==null?ruleList.Count-1:rules.CurrentRow.Index;rules.EndEdit();var r=ruleList[i];r.Applications=String.IsNullOrWhiteSpace(r.Applications)?name:r.Applications+", "+name;ruleList.ResetItem(i);}
        static string[] ProcessNames(){var names=new List<string>();foreach(var p in Process.GetProcesses())using(p)try{names.Add(p.ProcessName);}catch{}return names.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x).ToArray();}
        void RunningApps(){using(var d=new Form {Text="Choose a running application",ClientSize=new Size(400,430),StartPosition=FormStartPosition.CenterParent}){var list=new ListBox {Dock=DockStyle.Fill,Font=Font};list.Items.AddRange(ProcessNames());var add=new Button {Text="Use selected application",Dock=DockStyle.Bottom,Height=40,DialogResult=DialogResult.OK};d.Controls.Add(list);d.Controls.Add(add);if(d.ShowDialog(this)==DialogResult.OK&&list.SelectedItem!=null)AddApp(list.SelectedItem.ToString());}}
        void MoveRule(int delta){if(rules.CurrentRow==null)return;int i=rules.CurrentRow.Index,j=i+delta;if(j<0||j>=ruleList.Count)return;rules.EndEdit();var r=ruleList[i];ruleList.RemoveAt(i);ruleList.Insert(j,r);rules.CurrentCell=rules.Rows[j].Cells[1];}
        void BuildDevice(){
            var page=Tab("Device");var stack=new FlowLayoutPanel {Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};page.Controls.Add(stack);stack.Controls.Add(new Label {Text="Feni address",AutoSize=true,ForeColor=Muted});url=new TextBox {Text=config.Url,Width=400,BackColor=Bg,ForeColor=Ink,Margin=new Padding(0,8,0,16)};stack.Controls.Add(url);stack.Controls.Add(AsyncButton("Connect / refresh",Connect,185));deviceInfo=new Label {Width=800,Height=110,ForeColor=Muted};stack.Controls.Add(deviceInfo);
            enabled=new CheckBox {Text="Run application reactions in the background",Checked=config.RunRules,Width=450,Height=35};enabled.CheckedChanged+=delegate {config.RunRules=enabled.Checked;config.Save();};stack.Controls.Add(enabled);ruleState=new Label {Width=800,Height=65,ForeColor=Muted};stack.Controls.Add(ruleState);stack.Controls.Add(Button("Save configuration",Save,190));stack.Controls.Add(new Label {Text="Closing the window keeps application reactions running in the notification area.\nUse the tray menu's Quit command to stop.\n\nAnimation code is compiled into Feni; startup, sleep and wake also work without the PC.\nApp reactions require Studio running. Menus, alerts and the white clock retain priority.",Width=900,Height=170,ForeColor=Muted,Margin=new Padding(0,25,0,0)});
        }
        void EnsureDevice(){if(device==null)throw new InvalidOperationException("Connect to Feni in the Device tab first.");}
        async Task Connect(){config.Url=url.Text.Trim();var candidate=new DeviceClient(config.Url);try{var info=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(await candidate.Get("/code"));if(Convert.ToString(info["engine"])!="cpp")throw new IOException("Flash firmware 3.5.0 or later first.");if(device!=null)device.Dispose();device=candidate;config.Save();installedRevision=Convert.ToString(info["revision"]);RefreshRevisionInfo();status.Text="Connected to Feni.";}catch{if(device!=candidate)candidate.Dispose();throw;}}
        void RefreshRevisionInfo(){if(deviceInfo!=null&&device!=null)deviceInfo.Text="Connected  /  "+device.Url+"\nAnimation engine: C++ drawing code\nInstalled code revision: "+installedRevision+"\nSaved code revision: "+project.Revision;}
        async Task SendActivity(){if(busy)return;busy=true;try{if(device==null)await Connect();var saved=config.Rules.ToArray();var foreground=Foreground.Read();string[] running=saved.Any(r=>r.Enabled&&r.Trigger=="Running")?ProcessNames():new string[0];bool foregroundActivity=false;int slot=config.RunRules?Slots.Choose(saved,foreground.Name,running,foreground.Title,out foregroundActivity):6;int activity=slot==4?1:slot==5?2:slot>=7?3:0;var values=Fields("activity",activity);values.Add("foreground",foregroundActivity?"1":"0");int aiState=slot==5&&foregroundActivity?(aiOverride>=0?aiOverride:await AiStatus.ReadAsync(foreground)):0;values.Add("aiState",aiState.ToString());if(activity==3)values.Add("animation",slot.ToString());await device.Post("/pc",values);ruleState.Text=(config.RunRules?"Reactions active":"Reactions paused")+"  /  "+Slots.Names[slot]+(slot==5?" / "+AiStatus.Name(aiState)+(aiOverride>=0?" (manual)":" (automatic)"):"")+"\nPC connection healthy";}catch(Exception ex){ruleState.Text="Waiting to reconnect: "+ex.Message;}finally{busy=false;}}
        static Dictionary<string,string> Fields(string key,int value){return new Dictionary<string,string>{{key,value.ToString()}};}
        void OpenGuide(){string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Code guide.txt");if(File.Exists(path))Process.Start("notepad.exe",'"'+path+'"');}
        public void SaveScreenshot(string path){using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new Rectangle(0,0,Width,Height));bitmap.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}
    }
    static class Program {
        [DllImport("user32.dll")]static extern uint RegisterWindowMessage(string name);
        [DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint message,IntPtr w,IntPtr l);
        internal static int ShowMessage=(int)RegisterWindowMessage("FeniStudio.ShowWindow");
        [STAThread]static int Main(string[] args){
            try {
                if(args.Length==2&&args[0]=="--generate-header"){File.WriteAllText(args[1],CodeProject.Load().Header());return 0;}
                if(args.Length==1&&args[0]=="--self-test"){SelfTest.Run();return 0;}
                if(args.Length==2&&args[0]=="--ai-status"){var fg=Foreground.Read();int state=AiStatus.ReadAsync(fg).GetAwaiter().GetResult();File.WriteAllText(args[1],new JavaScriptSerializer().Serialize(new {process=fg.Name,state=state,label=AiStatus.Name(state)}));return 0;}
                bool created;using(var mutex=new Mutex(true,"Local\\FeniStudio",out created)) {
                    if(!created){PostMessage(new IntPtr(0xffff),(uint)ShowMessage,IntPtr.Zero,IntPtr.Zero);return 0;}
                    Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);var form=new StudioForm(StudioConfig.Load(),args.Contains("--tray"));
                    if(args.Length==2&&args[0]=="--screenshot"){var timer=new System.Windows.Forms.Timer {Interval=1200};timer.Tick+=delegate {timer.Stop();form.SaveScreenshot(args[1]);};timer.Start();}
                    Application.Run(form);
                }return 0;
            }catch(Exception ex){if(args.Length>0){Console.Error.WriteLine(ex.ToString());File.WriteAllText(Path.Combine(Path.GetTempPath(),"feni-studio-error.log"),ex.ToString());}else MessageBox.Show(ex.Message,"Feni Studio",MessageBoxButtons.OK,MessageBoxIcon.Error);return 1;}
        }
    }
}
